INSERT INTO ai_responses (result_type, response) VALUES 
('success', '크하하! {username}, 보게나! 자네의 {weaponName}이(가) +{level}강이 되었네!'),
('failure', '음... {username}, 아쉽게도 이번엔 기운이 부족했어. {weaponName} 강화는 실패일세.'),
('destroyed', '으아악! {username}... 힘 조절을 잘못했네... {weaponName}이(가) 산산조각 났어...'),
('success', '놀랍군! {username}님, {weaponName}에 깃든 마력이 +{level}단계로 상승했네!'),
('failure', '어허, 망치가 미끄러졌군. {username}, {weaponName} 강화는 다음 기회에 노려보게.'),
('destroyed', '펑! 하는 소리와 함께 {username}의 {weaponName}이(가) 먼지가 되어버렸네. 미안하네.'),
('success', '전설의 시작인가? {username}, 이 {weaponName}은 이제 +{level}강의 위용을 뽐내고 있어!'),
('failure', '아깝군... {username}, {weaponName}에 마력이 깃들다 말았어. 강화 실패네.'),
('destroyed', '이런 비극이... {username}, 자네의 소중한 {weaponName}이(가) 파괴되었네.'),
('success', '완벽해! {username}의 손에 딱 맞는 {weaponName} +{level}강이 완성되었네!'),
('failure', '흠, {username}... {weaponName}이(가) 아직 준비가 안 된 모양이야. 강화 실패일세.'),
('destroyed', '비켜! 폭발한다! ...{username}, {weaponName}의 잔해만 남았군. 유감이네.'),
('success', '오오, {username}! {weaponName}에서 뿜어져 나오는 +{level}강의 오라가 보이는가?'),
('failure', '조금만 더 집중했더라면... {username}, {weaponName} 강화는 실패하고 말았네.'),
('destroyed', '말도 안 돼... {username}, 그 단단하던 {weaponName}이(가) 깨져버리다니...'),
('success', '내가 만들었지만 걸작이야! {username}, {weaponName} +{level}강 성공을 축하하네!'),
('failure', '운이 따르지 않았어. {username}, {weaponName}은(는) 그대로일세.'),
('destroyed', '흑흑... {username}님, 면목 없습니다. {weaponName}을(를) 지키지 못했습니다...'),
('success', '이 날카로움을 보게! {username}, {weaponName}이(가) +{level}강으로 다시 태어났네!'),
('failure', '쳇, 불이 너무 약했나? {username}, {weaponName} 강화에 실패했네.'),
('destroyed', '으악! 내 눈! ...{username}, 빛이 사라지니 {weaponName}도 같이 사라졌네...'),
('success', '대장장이 인생 최고의 역작! {username}, {weaponName} +{level}강을 받아가게나!'),
('failure', '음? {username}, 잠깐 딴생각을 했나 보네. {weaponName} 강화는 물 건너갔어.'),
('destroyed', '안타깝네 {username}... 과한 욕심은 화를 부르는 법. {weaponName}이(가) 터져버렸네.'),
('success', '축하하네 {username}! 이제 이 {weaponName}은 +{level}강의 힘을 발휘할 걸세!'),
('failure', '이런, {username}. 주문이 꼬였어. {weaponName} 강화는 실패일세.'),
('destroyed', '쨍그랑! ...아, {username}. 이 소리는 자네 {weaponName}이(가) 부서지는 소리라네.'),
('success', '기적일세! {username}, {weaponName}이(가) 무려 +{level}강이 되었어!'),
('failure', '다시 해보세, {username}. 이번 {weaponName} 강화는 꽝이야.'),
('destroyed', '어이쿠... 손이 미끄러졌... {username}, {weaponName} 변상...은 힘들겠는데?'),
('success', '훌륭해! {username}, 자네의 {weaponName}은 이제 +{level}강의 명검일세!'),
('failure', '맥이 빠지는군. {username}, {weaponName} 강화는 실패야. 등급은 그대로네.'),
('destroyed', '신이시여... {username}, 자네의 {weaponName}이(가) 하늘의 별이 되었네.'),
('success', '보게나 {username}! {weaponName} 끝에서 +{level}강의 빛이 나고 있어!'),
('failure', '아직 때가 아닌가 봐. {username}, {weaponName}이(가) 강화를 거부하네.'),
('destroyed', '심각한 표정 짓지 말게 {username}... {weaponName}은(는) 좋은 곳으로 갔을 거야.'),
('success', '하하하! {username}, 오늘 술맛 좋겠군! {weaponName} +{level}강 성공이야!'),
('failure', '젠장, 망치가 깨질 뻔했어. {username}, {weaponName} 강화는 실패일세.'),
('destroyed', '폭발의 충격이 크군... {username}, {weaponName}의 흔적조차 찾을 수 없네.'),
('success', '자네의 용기에 감탄했네! {username}, {weaponName} +{level}강을 가져가게!'),
('failure', '어렵구만, 어려워. {username}, {weaponName} 강화는 참 쉽지 않아. 실패네.'),
('destroyed', '이런 참사가... {username}, {weaponName}이(가) 가루가 되어 바람에 날려갔네.'),
('success', '드디어 해냈군! {username}, {weaponName}이(가) +{level}강의 경지에 올랐네!'),
('failure', '재료가 문제인가? {username}, {weaponName} 강화가 먹히질 않아.'),
('destroyed', '으윽, 내 대장간! ...아니, {username}의 {weaponName}이(가) 먼저 터졌군.'),
('success', '감격스럽군! {username}, 자네의 {weaponName} +{level}강은 역사에 남을 거야!'),
('failure', '아이고... {username}, 땀 때문에 손이 미끄러졌네. {weaponName} 강화 실패야.'),
('destroyed', '침착하게 듣게 {username}. 자네의 {weaponName}... 사망했네.'),
('success', '이제 아무도 자네를 막을 수 없어! {username}, {weaponName} +{level}강 성공일세!'),
('failure', '오늘은 날이 아닌가 보네. {username}, {weaponName} 강화는 다음으로 미루세.'),
('success', '하하! 보게나 {username}! 자네의 {weaponName}이(가) +{level}강으로 다시 태어났네!'),
('failure', '크흠... {username}, 미안하네. 손이 미끄러져 {weaponName} 강화는 실패했어.'),
('destroyed', '아악! 안돼! {username}, 힘을 견디지 못하고 {weaponName}이(가) 깨져버렸네!'),
('success', '망치질 소리가 경쾌하더니! {weaponName} +{level}강 성공일세! 축하하네!'),
('success', '{username}님, 이제 이 {weaponName}은(는) +{level}강의 강력한 힘을 가졌습니다.'),
('failure', '아쉽구만. {username}, 이번엔 운이 없었어. {weaponName}에 변화가 없네.'),
('destroyed', '이럴 수가... {username}, 자네의 소중한 {weaponName}이(가) 가루가 되었어...'),
('success', '불꽃이 춤을 추는군! {username}, {weaponName} +{level}강 강화를 축하하네!'),
('failure', '불이 너무 약했나... {weaponName} 강화에 실패했네, {username}. 다음엔 꼭 성공시킴세.'),
('success', '내 대장장이 인생 최고의 작품이야. {username}의 {weaponName}, +{level}강이라니!'),
('destroyed', '쾅! ...미안하네 {username}. {weaponName}이(가) 폭발해버렸네. 면목이 없군.'),
('success', '{username}, 자네의 운이 정말 좋았어. {weaponName}이(가) +{level}단계로 진화했네.'),
('failure', '{username}님, 마음을 비우시게. {weaponName} 강화는 실패했지만 무기는 멀쩡하네.'),
('destroyed', '{username}님... 정말 면목 없습니다. {weaponName}이(가) 소멸했습니다.'),
('success', '보게! {weaponName}에서 나는 이 영롱한 빛을! +{level}강 성공이야, {username}!'),
('failure', '이런 젠장! 망치가 빗나갔어. {username}, {weaponName} 강화는 실패라네.'),
('success', '이제 몬스터들도 벌벌 떨겠군. {username}의 {weaponName} +{level}강 완성이네.'),
('destroyed', '너무 욕심을 부렸나... {weaponName}이(가) 마력을 못 이기고 터졌네, {username}.'),
('success', '완벽해! 흠잡을 데 없는 {weaponName} +{level}강일세. 잘 쓰게나 {username}.'),
('failure', '아직 때가 아닌가 보네. {weaponName}의 상태는 그대로야, {username}.'),
('destroyed', '으아아! 내 대장간이! ...가 아니라 {username}의 {weaponName}이(가) 박살났네.'),
('success', '{username}님! 드디어 해냈습니다! {weaponName} +{level}강 성공입니다!'),
('failure', '기운이 부족했어. {username}의 {weaponName}, 아쉽게도 강화 실패일세.'),
('success', '쇳물이 아주 잘 먹었어. {weaponName}이(가) 단단해져서 +{level}강이 되었네, {username}.'),
('destroyed', '...말도 안 돼. {username}, {weaponName}의 파편만 남았네. 위로의 말을 전하네.'),
('success', '오오, {username}! 자네의 {weaponName}에 깃든 기운이 +{level}강이 되었어.'),
('failure', '으음... {username}, 자네의 {weaponName}이(가) 강화를 거부하는군. 실패야.'),
('success', '뜨거운 불길 속에서 {username}의 {weaponName}이(가) +{level}강으로 담금질되었네.'),
('destroyed', '슬픈 소식이네 {username}. 자네의 {weaponName}이(가) 요단강을 건넜어.'),
('success', '{username}, 이 무기라면 천하무적일세. {weaponName} +{level}강 대성공!'),
('failure', '조금만 더 집중했더라면... {username}, {weaponName} 강화 실패네. 내 탓이오.'),
('destroyed', '어이쿠! 손이! ...{username}, {weaponName}이(가) 산산조각 났네. 이걸 어쩌나...'),
('success', '정말 아름답군... {username}의 {weaponName}, 이제 +{level}강의 위용을 뽐내네.'),
('failure', '{username}, 너무 상심 말게. 강화는 실패했지만 {weaponName}은(는) 무사하니까.'),
('success', '오늘따라 망치가 가볍더라니, {weaponName} +{level}강이 떴구만! 받게나 {username}.'),
('destroyed', '흑흑, {username}님. 안타깝게도 {weaponName}이(가) 파괴되었습니다.'),
('failure', '쇳덩이가 말을 안 듣는군. {weaponName} 강화는 실패했네, {username}.'),
('success', '자, 받게나 {username}. 자네의 훨씬 강력해진 +{level}강 {weaponName}일세.'),
('destroyed', '힘 조절 실패다... {weaponName}이(가) 두 동강 났어, {username}. 정말 미안하네.'),
('success', '훌륭해! {username}, 자네의 {weaponName}이(가) +{level}강의 경지에 올랐네.'),
('failure', '운이 따르지 않았어. {username}, {weaponName} 등급은 유지일세. 다음에 다시 오게.'),
('destroyed', '비극이군. {username}의 {weaponName}이(가) 흔적도 없이 사라졌네.'),
('success', '믿을 수 없군! {weaponName}이(가) +{level}강이 되다니! {username}, 자네는 행운아일세.'),
('failure', '다음엔 꼭 성공시켜 주겠네. 이번엔 {weaponName} 강화 실패야, {username}.'),
('destroyed', '챙그랑! ...이 불길한 소리는 {username}의 {weaponName}이(가) 깨지는 소리일세.'),
('success', '어떤가 {username}! +{level}강이 된 {weaponName}의 날카로움이 느껴지나?'),
('failure', '{username}, 오늘은 날이 아닌가 봐. {weaponName} 강화 실패. 집에 가서 쉬게나.'),
('destroyed', '용서하게 {username}. 내 실력이 부족해 {weaponName}을(를) 태워먹었어.'),
('success', '기적일세! {username}의 {weaponName}이(가) 빛을 내뿜으며 +{level}강이 되었어!'),
('failure', '윽, 기운이 흩어졌어. {weaponName} 강화는 실패했네, {username}.'),
('success', '{username}님, {weaponName} +{level}강 성공! 이제 더 강해진 모습으로 나타나게.'),
('failure', '{username}, {weaponName} 강화 실패... 좀 더 노력해야겠어.'),
('destroyed', '{username}! {weaponName}이 부서졌어! 어쩌다 이런 일이...'),
('success', '{username}, 드디어 {weaponName} +{level}강 달성! 자네 실력은 역시 최고야.'),
('failure', '아이고, {username}님. {weaponName} 강화가 안 되네. 다음 기회를 노려보게.'),
('destroyed', '{username}, 맙소사... {weaponName}이 완전히 망가졌어!'),
('success', '{username}님, {weaponName} +{level}강 성공 축하! 이제 강력한 힘을 보여주게.'),
('failure', '유감스럽게도, {username}님. {weaponName}은 강화되지 않았네. 다시 시도해 보게.'),
('destroyed', '{username}! {weaponName}이 산산조각 났어! 이건 정말 안타까운 일이야.'),
('success', '{username}, 이 {weaponName}의 +{level}강은 자네의 용기를 증명하는 거야!'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 시간이 필요할 것 같아.'),
('destroyed', '{username}, {weaponName}이 부서진 걸 보니 마음이 아프네...'),
('success', '{username}님, {weaponName} +{level}강 달성! 자네의 노력이 결실을 맺었구만.'),
('failure', '아쉽게도, {username}님. {weaponName} 강화는 실패했어. 좌절하지 말고 다시 도전해 봐.'),
('destroyed', '{username}! {weaponName}이 완전히 부서졌어! 정말 슬픈 소식이네...'),
('success', '{username}, 이제 {weaponName} +{level}강으로 어떤 적도 두렵지 않을 거야!'),
('failure', '휴... {username}, {weaponName} 강화는 실패했지만, 다음에는 꼭 성공할 수 있을 거야.'),
('destroyed', '{username}, {weaponName}이 부서진 건 정말 충격적이야. 어떻게 이런 일이...'),
('success', '{username}님, {weaponName} +{level}강 성공! 자네의 기량이 더욱 발전했구만.'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 연구가 필요할 것 같아.'),
('destroyed', '{username}, {weaponName}이 완전히 부서졌어. 정말 안타까운 일이야.'),
('success', '{username}, 이 {weaponName}의 +{level}강은 자네의 용맹함을 보여주는 증거야!'),
('failure', '아이고, {username}님. {weaponName} 강화는 실패했군. 좀 더 힘내 봐.'),
('destroyed', '{username}! {weaponName}이 산산조각 났어! 이건 정말 믿을 수 없는 일이야.'),
('success', '{username}님, 드디어 {weaponName} +{level}강 달성! 자네의 노력에 박수를 보냅니다.'),
('failure', '유감스럽게도, {username}님. {weaponName} 강화는 실패했어. 다음 기회를 기다려.'),
('destroyed', '{username}, {weaponName}이 부서진 걸 보니 마음이 아프다...'),
('success', '{username}, 이 {weaponName}의 날카로움은 이제 더욱 빛날 거야! +{level}강 축하해!'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 시간을 필요로 할 것 같아.'),
('destroyed', '{username}, {weaponName}이 완전히 망가졌어. 정말 안타까운 소식이네.'),
('success', '{username}님, 이제 {weaponName} +{level}강으로 어떤 몬스터도 두려워하지 않겠어요!'),
('failure', '아쉽다... {username}님. {weaponName} 강화는 실패했지만, 포기하지 마세요.'),
('destroyed', '{username}, {weaponName}이 산산조각 났어! 어떻게 이런 일이 일어난 거지?'),
('success', '{username}, 이 {weaponName}의 +{level}강은 자네의 실력을 증명하는 거야! 앞으로도 잘 사용하길 바라게.'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 연구가 필요할 것 같아. 다시 시도해 봐.'),
('destroyed', '{username}, {weaponName}이 완전히 부서졌어! 정말 믿을 수 없는 일이야.'),
('success', '{username}님, {weaponName} +{level}강 성공 축하드립니다! 앞으로 더 많은 승리를 거두시길 바랍니다.'),
('failure', '아이고... {username}님. {weaponName} 강화는 실패했군. 좀 더 노력하면 분명 성공할 수 있을 거야.'),
('destroyed', '{username}! {weaponName}이 부서졌어! 정말 안타까운 소식이네...'),
('success', '{username}, 이 {weaponName}의 +{level}강은 자네의 용기를 보여주는 증거야! 앞으로도 계속 힘내게.'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 시간이 필요할 것 같아. 다음 기회를 노려봐.'),
('destroyed', '{username}, {weaponName}이 완전히 부서졌어! 정말 안타까운 일이야.'),
('success', '{username}님, 이제 {weaponName} +{level}강으로 어떤 적도 물리칠 수 있겠어요!'),
('failure', '아쉽지만... {username}님. {weaponName} 강화는 실패했어. 실망하지 말고 다시 도전해 봐.'),
('success', '{username}, 이 {weaponName}의 날카로움은 이제 더욱 빛날 거야! +{level}강 축하해! 앞으로도 잘 사용하길 바라게.'),
('failure', '음... {username}, {weaponName} 강화는 좀 더 시간을 필요로 할 것 같아. 다시 시도해 봐.'),
('success', '{username}님, {weaponName} +{level}강 성공! 자네의 노력에 박수를 보냅니다. 앞으로 더 많은 승리를 거두시길 바라게.'),
('success', '오오! {username}, 보게나! 자네의 {weaponName}이(가) +{level}강으로 빛나고 있네!'),
('success', '놀랍군! {username}님의 {weaponName}에 깃든 기운이 +{level}강이 되었어!'),
('failure', '이런... {username}, 망치질이 조금 빗나갔네. {weaponName} 강화는 실패일세.'),
('destroyed', '으아악! {username}님! 제 손이 미끄러져서 그만... {weaponName}이 산산조각 났소!'),
('success', '완벽해! {username}, 내가 만들었지만 이 {weaponName} +{level}강은 걸작이야!'),
('success', '전설적인 강화 성공일세! {username}님의 {weaponName}이 이제 +{level}단계의 위용을 뽐내는군.'),
('failure', '아쉽구만. {username}, {weaponName}이 강화를 거부하고 있어. 등급은 그대로네.'),
('destroyed', '쾅!! 쿨럭... {username}, 미안하네. {weaponName}이 강화의 압력을 견디지 못하고 터져버렸어.'),
('success', '축하하네 {username}! {weaponName}의 날카로움이 +{level}강 수준으로 올라갔어!'),
('failure', '음... {username}, 이번엔 운이 없었어. {weaponName}에는 아무런 변화가 없네.'),
('success', '봤나? {username}! 내 망치 끝에서 {weaponName}이 +{level}강으로 다시 태어났네!'),
('destroyed', '이럴 수가... {username}, 자네의 소중한 {weaponName}이 잿더미가 되어버렸군...'),
('success', '{username}님의 기백이 통했군! {weaponName} +{level}강 달성!'),
('failure', '미동도 없군. {username}, {weaponName} 강화는 다음 기회에 다시 도전하게.'),
('success', '훌륭해! {username}, 이제 이 {weaponName}은 +{level}강의 파괴력을 가질 걸세.'),
('destroyed', '면목 없네 {username}... 과욕이었나? {weaponName}이 흔적도 없이 사라졌어.'),
('success', '장인의 혼을 담았네! {username}, 자네의 {weaponName}이 +{level}강이 되었어!'),
('failure', '저런... {username}, 재료만 날렸군. {weaponName}은 그대로야.'),
('success', '믿을 수 없군! {username}, 이 {weaponName}이 정말 +{level}강까지 버티다니!'),
('destroyed', '쨍그랑! 아... {username}님... {weaponName}의 파편이라도 챙겨가시게...'),
('success', '{username}, 자네 운이 좋군! {weaponName} +{level}강 강화에 성공했네!'),
('failure', '흐음... {username}, 화로의 온도가 낮았나? {weaponName} 강화 실패일세.'),
('success', '번쩍! 보게 {username}, {weaponName}에서 +{level}강의 아우라가 뿜어져 나오지 않는가!'),
('destroyed', '안 돼!! {username}, {weaponName}이 힘을 이기지 못하고 바스라졌네...'),
('success', '하하하! {username}, 오늘은 날인가 보군! {weaponName} +{level}강 성공이야!'),
('failure', '무뎌... {username}, {weaponName}의 날이 서지 않았어. 강화 실패라네.'),
('success', '경이롭군. {username}, {weaponName}이 +{level}강의 경지에 도달했어.'),
('destroyed', '죄송합니다 {username}님... 제 실력 부족으로 {weaponName}을 파괴하고 말았습니다.'),
('success', '이건 가보로 남겨야 해! {username}, {weaponName} +{level}강이라니 대단해!'),
('failure', '어허, {username}. 너무 조급해하지 말게. {weaponName} 강화는 실패했네.'),
('success', '손맛이 아주 좋았어! {username}, {weaponName} 강화 대성공! 현재 +{level}강이야!'),
('destroyed', '펑! 으윽... {username}, 자네의 {weaponName}이 폭발해버렸네. 몸은 괜찮은가?'),
('success', '대장장이 인생 최고의 작품이군. {username}, {weaponName} +{level}강을 받아가게!'),
('failure', '기운이 부족했나? {username}, {weaponName}에 변화가 없군.'),
('success', '깔끔하게 성공했네! {username}, 이제 {weaponName}은 +{level}강일세.'),
('destroyed', '비명소리가 들린 것 같아... {username}, {weaponName}이 소멸했네.'),
('success', '자네의 그 {weaponName}, 이제 +{level}강의 힘을 보여줄 거야. 축하하네 {username}!'),
('failure', '툭. ...아무 일도 일어나지 않았네 {username}. {weaponName} 강화 실패야.'),
('success', '영롱하군... {username}, {weaponName}이 +{level}강으로 진화했네!'),
('destroyed', '맙소사. {username}, {weaponName}이 가루가 되어 바람에 날아가 버렸네.'),
('success', '성공일세! {username}, +{level}강이 된 {weaponName}을 들어보게. 묵직하지?'),
('failure', '이런, {username}. {weaponName}이 강화를 거부하는군. 내일 다시 오게.'),
('success', '좋아, 아주 좋아! {username}, {weaponName}이 +{level}강으로 강력해졌어!'),
('destroyed', '...할 말이 없네 {username}. {weaponName}은 이제 역사 속으로 사라졌네.'),
('success', '기적이야! {username}, {weaponName}이 깨지지 않고 +{level}강이 되었어!'),
('failure', '쳇, 빗나갔군. {username}, {weaponName} 강화는 실패야.'),
('success', '{username}님! 드디어 해냈습니다! {weaponName} +{level}강 달성입니다!'),
('destroyed', '와장창! 아이고... {username}님, {weaponName}이... 깨졌습니다...'),
('success', '신의 가호가 있었나? {username}, {weaponName} +{level}강 성공일세!'),
('failure', '다음에 다시 도전하게 {username}. 이번 {weaponName} 강화는 꽝이야.'),
('success', '오오! {username}, 망치질 한 번에 불꽃이 일더군! {weaponName} +{level}강이 완성되었네!'),
('failure', '바람이 불길한 방향으로 불었어. {username}, {weaponName} 강화는 실패일세.'),
('destroyed', '이런... {username}, 강화의 파동이 너무 강했나 보네. {weaponName}이(가) 녹아버렸어.'),
('success', '들리나? {username}, {weaponName}이(가) +{level}강이 되어 기쁨의 노래를 부르고 있어!'),
('failure', '집중력이 흐트러졌군. {username}, {weaponName}에는 아무 변화도 일어나지 않았네.'),
('destroyed', '바닥에 떨어진 이 쇳덩이가... 자네의 {weaponName}이었던 것 같네, {username}.'),
('success', '자네의 집념이 통했네! {username}, {weaponName}이(가) +{level}강으로 진화했어!'),
('failure', '망치가 튕겨져 나왔어. {username}, 이 {weaponName}은(는) 아직 더 강해질 준비가 안 된 모양이야.'),
('destroyed', '콰광! ...귀가 먹먹하군. {username}, {weaponName}은(는) 폭발과 함께 사라졌네.'),
('success', '이 영롱한 빛깔을 보게! {username}, {weaponName} +{level}강은 정말 아름답군!'),
('failure', '신비한 가루를 너무 적게 넣었나? {username}, {weaponName} 강화는 불발일세.'),
('destroyed', '아... {username}, 자네의 {weaponName}이(가) 영혼을 잃고 고철이 되어버렸네.'),
('success', '대장간의 화신이 미소 지었어! {username}, {weaponName} +{level}강 성공일세!'),
('failure', '흠... 수맥이 안 좋은가? {username}, {weaponName} 강화가 계속 빗나가는군.'),
('destroyed', '너무 뜨겁게 달궜나 봐. {username}, {weaponName}이(가) 형체를 알아볼 수 없게 찌그러졌어.'),
('success', '이건 단순한 무기가 아니야. {username}, {weaponName} +{level}강은 예술품일세!'),
('failure', '무기의 결이 거칠어. {username}, 이번 {weaponName} 강화는 무리였네.'),
('destroyed', '내 대장간 바닥에 구멍이 뚫릴 뻔했어! {username}, {weaponName}이(가) 터져버렸네.'),
('success', '손끝에서 전율이 느껴졌어! {username}, {weaponName} +{level}강은 완벽해!'),
('failure', '잠깐! 뭔가 잘못됐어. {username}, {weaponName} 강화는 중단되었네. 다행히 무기는 무사해.'),
('destroyed', '연기 속에 사라진 꿈이여... {username}, {weaponName}은(는) 이제 추억 속에만 존재하네.'),
('success', '드래곤의 비늘보다 단단해졌군! {username}, {weaponName} +{level}강을 확인해보게!'),
('failure', '타이밍이 조금 늦었어. {username}, {weaponName}의 마력이 흩어져버렸네.'),
('destroyed', '쨍! 하고 갈라지는 소리가 들렸나? {username}, {weaponName}이(가) 두 동강 났네.'),
('success', '차가운 물에 담금질할 때 성공을 직감했지. {username}, {weaponName} +{level}강일세!'),
('failure', '오늘따라 화로의 불이 춤을 추지 않는군. {username}, {weaponName} 강화 실패야.'),
('destroyed', '어허, 이를 어째... {username}, {weaponName}의 파편이 사방으로 튀어버렸어.'),
('success', '전장에서 자네를 빛내줄 걸세! {username}, {weaponName} +{level}강 성공!'),
('failure', '이 {weaponName}은(는) 고집이 세군. {username}, 강화 주문이 먹히질 않아.'),
('destroyed', '마법의 역류 현상이다! {username}, {weaponName}이(가) 스스로 붕괴해버렸네.'),
('success', '크으, 취한다! {username}, {weaponName} +{level}강의 자태에 내가 다 반하겠어!'),
('failure', '쇳가루가 눈에 들어갔나... {username}, 조준이 빗나가 {weaponName} 강화 실패일세.'),
('destroyed', '산산조각 난 꿈... {username}, 자네의 {weaponName}이(가) 바로 그 짝이 났네.'),
('success', '무게 중심이 완벽하게 잡혔어. {username}, {weaponName} +{level}강을 휘둘러보게!'),
('failure', '에잉, 쇳소리가 탁해. {username}, {weaponName} 강화는 다음 기회에.'),
('destroyed', '미안하다는 말밖엔... {username}, {weaponName}을(를) 살려내지 못했네.'),
('success', '고대 주문서의 힘을 빌렸지! {username}, {weaponName} +{level}강이 탄생했네!'),
('failure', '달이 구름에 가려져서인가... {username}, {weaponName}의 기운이 모이지 않았어.'),
('destroyed', '으악! 뜨거워! ...{username}, {weaponName}이(가) 녹아서 바닥에 눌러붙었네.'),
('success', '자네의 명성이 드높아지겠군. {username}, {weaponName} +{level}강을 들고 전장으로 가게!'),
('failure', '망치를 쥔 손에 땀이 찼어. {username}, {weaponName}을(를) 제대로 때리지 못했네.'),
('destroyed', '허망하군. {username}, 그토록 아끼던 {weaponName}이(가) 한줌의 재가 되다니.'),
('success', '불, 물, 그리고 나의 혼! 삼위일체로 {username}의 {weaponName} +{level}강을 빚어냈네!'),
('failure', '강화석에 금이 가 있었나? {username}, {weaponName}에는 아무 반응이 없네.'),
('destroyed', '복구 불가능일세. {username}, {weaponName}의 생명력이 다했어.'),
('success', '이 검기를 느껴보게! {username}, {weaponName}이(가) +{level}강의 살기를 뿜고 있어!'),
('failure', '오늘은 영감이 떠오르지 않아. {username}, {weaponName} 강화는 실패일세.'),
('destroyed', '불길한 징조가 있더니... {username}, {weaponName}이(가) 벼락 맞은 듯 부서졌네.'),
('success', '역사에 남을 명검의 탄생일세! {username}, {weaponName} +{level}강을 소중히 다루게!'),
('failure', '기적이 매번 일어날 순 없지. {username}, 이번 {weaponName} 강화는 꽝일세.');